### ISSUE TITLE
doesn't work on kernel 5.7.7

### ISSUE THREAD

**Issue by DocMAX** [AMV007/alx_dkms_installer#1]
```
Preparing dkms module source...
Using 5.4+ patch...
Done
alx-wol, 5: added
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/i2c-piix4-aura/5.3.11/source/dkms.conf does not exist.
uninstalling dkms module
Error! There are no instances of module: alx
5.7.7 located in the DKMS tree.
!!! there is some error

```

**Comment by DocMAX** [comment]
nevermind. is not related to your code.

**Comment by DocMAX** [comment]
Reopen because although i can set WOL to "pg" it's not working. Windows is working with the same BIOS settings. There is no LINK on linux after suspend. Running Arch Linux with latest kernel 5.7.9.

**Comment by hrt070** [comment]
I see the same problem. Fedora 31 and 32 with kernel 5.6.15
Used to work fine with 5.3.16

**Comment by jansohn** [comment]
@DocMAX @hrt070 the patch provided here did not work for me either. The one provided in the official bug report comments (https://bugzilla.kernel.org/show_bug.cgi?id=61651#c147) does work for me though with latest kernel 5.10.

**Comment by AMV007** [comment]
@jansohn updated 000-enable-alx-wol-5.4.x.patch from forum link
