### ISSUE TITLE
error  setup: ligne 103: `}'

### ISSUE THREAD

**Issue by flexo44** [AMV007/alx_dkms_installer#8]
Hello,

I tried to launch the setup. 
But it returns me the error : 
setup: ligne 103: erreur de syntaxe près du symbole inattendu « } »

setup: ligne 103: `}'

Thank you in advance for your help and feedback.

**Comment by 4w4z4rd** [comment]
> Hello,
> 
> I tried to launch the setup. But it returns me the error : setup: ligne 103: erreur de syntaxe près du symbole inattendu « } »
> 
> setup: ligne 103: `}'
> 
> Thank you in advance for your help and feedback.

Hello flexo44.

In the setup file, I made a change on line 66 where I replaced 'if' with 'elif'. I also deleted lines 71 to 74 because they are repeated in lines 61 to 64. These modifications worked for me.
